#!/bin/bash
#QR Generator by Rania Amina. Original source https://gist.github.com/elbym/97e7ed08b0c1e94d826e

clear
printf "==========================
Tulis Nama Berkas CSV Anda
==========================\n
Contoh Penulisan: \nBerkas.csv, /home/user/Berkas.csv, atau ../Berkas.csv\n\n"
# choose the database
read -p "Berkas: " DATACSV

# export option
echo
echo 'Pilih format ekspor yang Anda inginkan?'
select TYPE in SVG PNG EPS ASCII
do
        case $TYPE in 
        SVG|PNG|EPS|ASCII)   
                break
                ;;
        *)
                echo "Pilihan salah, ulangi!" 
                ;;
        esac
done

if [[ $DATACSV != *.csv ]]
then
  clear 
  echo "Maaf, QR Generator hanya mendukung berkas *.csv :("
  echo "Silakan jalankan kembali dan masukkan berkas yang benar!"
  exit 1
else
  i=0
  while read line
  do
    #create folder
    TEMPAT_OUTPUT=Hasil
    if [ ! -d $TEMPAT_OUTPUT ]
    then
        mkdir $TEMPAT_OUTPUT
     fi
  
    #create and choose variables
    var1=$(cut -d ',' -f1 <<< "$line")
    var2=$(cut -d ',' -f2 <<< "$line")
    var3=$(cut -d ',' -f3 <<< "$line")
    var4=$(cut -d ',' -f4 <<< "$line")
  
    #terminal output
    echo $var1-$var2-$var3 Ok!
    
    #first, check i value
    if [[ "$i" -eq "0" ]]
    then
      # going to next loop
      i=1
      continue
    else
      # otherwise, generate QR-code when reach 2nd line
      qrencode -t $TYPE -d 96 -s 30 -l H -o "Hasil/$var4".$TYPE "$var1 $var2 $var3"
    fi    
   #database name
  done < $DATACSV
fi
echo 
read -n 1 -s -r -p "Tekan sembarang tombol untuk mengakhiri sesi..." 
    clear

