#!/bin/bash
read -e -p "Berkas Video Anda: " NamaBerkas
read -e -p "Nama Output: " OUTPUT
echo 'FPS?'
select FPS in 10 18 24 30
do
        case $FPS in 
        10|18|24|30)   
                break
                ;;
        *)
                echo "Pilihan salah, ulangi!" 
                ;;
        esac
done
echo 'Skala Gambar?'
select SCALE in 320 640 1280
do
        case $SCALE in 
        320|640|1280)   
                break
                ;;
        *)
                echo "Pilihan salah, ulangi!" 
                ;;
        esac
done
ffmpeg -i $NamaBerkas -filter_complex 'fps='$FPS',scale='$SCALE':-1:flags=lanczos,split [o1] [o2];[o1] palettegen [p]; [o2] fifo [o3];[o3] [p] paletteuse' $OUTPUT
