#!/bin/bash

#creating directory

mkdir -p image/drawable-mdpi
mkdir -p image/drawable-hdpi
mkdir -p image/drawable-xhdpi
mkdir -p image/drawable-xxhdpi
mkdir -p image/drawable-xxxhdpi

# enter directory
cd svg-image

# exoprting image
for i in *.svg; 
do 
rsvg-convert -a -d 96 -p 96 -h 210 -f png "$i" -o "../image/drawable-mdpi/${i%.*}.png";
rsvg-convert -a -d 96 -p 96 -h 315 -f png "$i" -o "../image/drawable-hdpi/${i%.*}.png";
rsvg-convert -a -d 96 -p 96 -h 420 -f png "$i" -o "../image/drawable-xhdpi/${i%.*}.png";
rsvg-convert -a -d 96 -p 96 -h 630 -f png "$i" -o "../image/drawable-xxhdpi/${i%.*}.png";
rsvg-convert -a -d 96 -p 96 -h 840 -f png "$i" -o "../image/drawable-xxxhdpi/${i%.*}.png"; 
done

cd ..

